package org.noodle.orm.mapper;

import java.util.List;
import org.noodle.orm.model.Exercise;

public interface ExerciseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int insert(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    Exercise selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    List<Exercise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Exercise record);
}