package org.noodle.orm.mapper;

import java.util.List;
import org.noodle.orm.model.Vocabulary;

public interface VocabularyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int insert(Vocabulary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    Vocabulary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    List<Vocabulary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vocabulary record);
}