package org.noodle.orm.mapper;

import java.util.List;
import org.noodle.orm.model.Words;

public interface WordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int insert(Words record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    Words selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    List<Words> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Words record);
}