package org.noodle.orm.model;

public class Exercise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.exercise_time
     *
     * @mbg.generated
     */
    private Long exerciseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.id
     *
     * @return the value of exercise.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.id
     *
     * @param id the value for exercise.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.user_id
     *
     * @return the value of exercise.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.user_id
     *
     * @param userId the value for exercise.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.exercise_time
     *
     * @return the value of exercise.exercise_time
     *
     * @mbg.generated
     */
    public Long getExerciseTime() {
        return exerciseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.exercise_time
     *
     * @param exerciseTime the value for exercise.exercise_time
     *
     * @mbg.generated
     */
    public void setExerciseTime(Long exerciseTime) {
        this.exerciseTime = exerciseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.score
     *
     * @return the value of exercise.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.score
     *
     * @param score the value for exercise.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.comment
     *
     * @return the value of exercise.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.comment
     *
     * @param comment the value for exercise.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}