package org.noodle.orm.model;

public class Words {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.dictionary_id
     *
     * @mbg.generated
     */
    private Long dictionaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.spelling
     *
     * @mbg.generated
     */
    private String spelling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.pronunciation
     *
     * @mbg.generated
     */
    private String pronunciation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.explanation
     *
     * @mbg.generated
     */
    private String explanation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.id
     *
     * @return the value of words.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.id
     *
     * @param id the value for words.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.dictionary_id
     *
     * @return the value of words.dictionary_id
     *
     * @mbg.generated
     */
    public Long getDictionaryId() {
        return dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.dictionary_id
     *
     * @param dictionaryId the value for words.dictionary_id
     *
     * @mbg.generated
     */
    public void setDictionaryId(Long dictionaryId) {
        this.dictionaryId = dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.spelling
     *
     * @return the value of words.spelling
     *
     * @mbg.generated
     */
    public String getSpelling() {
        return spelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.spelling
     *
     * @param spelling the value for words.spelling
     *
     * @mbg.generated
     */
    public void setSpelling(String spelling) {
        this.spelling = spelling == null ? null : spelling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.pronunciation
     *
     * @return the value of words.pronunciation
     *
     * @mbg.generated
     */
    public String getPronunciation() {
        return pronunciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.pronunciation
     *
     * @param pronunciation the value for words.pronunciation
     *
     * @mbg.generated
     */
    public void setPronunciation(String pronunciation) {
        this.pronunciation = pronunciation == null ? null : pronunciation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.explanation
     *
     * @return the value of words.explanation
     *
     * @mbg.generated
     */
    public String getExplanation() {
        return explanation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.explanation
     *
     * @param explanation the value for words.explanation
     *
     * @mbg.generated
     */
    public void setExplanation(String explanation) {
        this.explanation = explanation == null ? null : explanation.trim();
    }
}