package org.noodle.orm.mapper;

import java.util.List;
import org.noodle.orm.model.Dictionary;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated
     */
    Dictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated
     */
    List<Dictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dictionary record);

    /*------------------------------------------------------------*/

    /**
     * 查询用户所有关联的词典
     * @param userId 用户id
     */
    List<Dictionary> selectAllByUser(Long userId);

    /**
     * 查询用户关联的有效词典
     * @param userId 用户id
     */
    List<Dictionary> selectValidByUser(Long userId);

    /**
     * 根据名称条件查询有效的公用词典
     * @param nameCondition 名称
     * @return 有效的公用词典
     */
    List<Dictionary> selectPublicByCondition(String nameCondition);
}