package org.noodle.orm.mapper;

import java.util.List;
import org.noodle.orm.model.ExerciseWords;

public interface ExerciseWordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_words
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_words
     *
     * @mbg.generated
     */
    int insert(ExerciseWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_words
     *
     * @mbg.generated
     */
    ExerciseWords selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_words
     *
     * @mbg.generated
     */
    List<ExerciseWords> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise_words
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExerciseWords record);

    /*------------------------------------------------------------*/

    /**
     * 根据exerciseId查
     * @param exerciseId 测验id
     */
    List<ExerciseWords> selectByExerciseId(Long exerciseId);
}