package org.noodle.orm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.noodle.orm.model.Exercise;

public interface ExerciseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int insert(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    Exercise selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    List<Exercise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Exercise record);

    /*--------------------------------------------------*/

    /**
     * 根据用户查指定时间后的测验记录
     * @param userId 用户id
     * @param beginTime 指定时间的时间戳
     */
    List<Exercise> selectByUserId(@Param("userId") Long userId, @Param("beginTime") Long beginTime);
}