package org.noodle.orm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.noodle.orm.model.Recite;

public interface ReciteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recite
     *
     * @mbg.generated
     */
    int insert(Recite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recite
     *
     * @mbg.generated
     */
    Recite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recite
     *
     * @mbg.generated
     */
    List<Recite> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recite record);

    /*--------------------------------------------------*/

    /**
     * 根据用户查指定时间后的背诵记录
     * @param userId 用户id
     * @param beginTime 指定时间的时间戳
     */
    List<Recite> selectByUserId(@Param("userId") Long userId, @Param("beginTime") Long beginTime);
}