package org.noodle.orm.mapper;

import java.util.List;

import org.noodle.orm.model.ReciteWords;
import org.noodle.orm.model.ReviewWords;

public interface ReviewWordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_words
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_words
     *
     * @mbg.generated
     */
    int insert(ReviewWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_words
     *
     * @mbg.generated
     */
    ReviewWords selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_words
     *
     * @mbg.generated
     */
    List<ReviewWords> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_words
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReviewWords record);

    /*------------------------------------------------------------*/

    /**
     * 根据reviewId查
     * @param reviewId 复习id
     */
    List<ReviewWords> selectByReviewId(Long reviewId);
}