package org.noodle.orm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.noodle.orm.model.Recite;
import org.noodle.orm.model.Review;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    Review selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    List<Review> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Review record);

    /*--------------------------------------------------*/

    /**
     * 根据用户查指定时间后的复习记录
     * @param userId 用户id
     * @param beginTime 指定时间的时间戳
     */
    List<Review> selectByUserId(@Param("userId") Long userId, @Param("beginTime") Long beginTime);
}