package org.noodle.orm.model;

public class Dictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.publisher
     *
     * @mbg.generated
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.valid_flag
     *
     * @mbg.generated
     */
    private String validFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.public_flag
     *
     * @mbg.generated
     */
    private String publicFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.name
     *
     * @return the value of dictionary.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.name
     *
     * @param name the value for dictionary.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.publisher
     *
     * @return the value of dictionary.publisher
     *
     * @mbg.generated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.publisher
     *
     * @param publisher the value for dictionary.publisher
     *
     * @mbg.generated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.valid_flag
     *
     * @return the value of dictionary.valid_flag
     *
     * @mbg.generated
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.valid_flag
     *
     * @param validFlag the value for dictionary.valid_flag
     *
     * @mbg.generated
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag == null ? null : validFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.public_flag
     *
     * @return the value of dictionary.public_flag
     *
     * @mbg.generated
     */
    public String getPublicFlag() {
        return publicFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.public_flag
     *
     * @param publicFlag the value for dictionary.public_flag
     *
     * @mbg.generated
     */
    public void setPublicFlag(String publicFlag) {
        this.publicFlag = publicFlag == null ? null : publicFlag.trim();
    }
}