package org.noodle.orm.model;

public class ExerciseWords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_words.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_words.exercise_id
     *
     * @mbg.generated
     */
    private Long exerciseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_words.vocabulary_id
     *
     * @mbg.generated
     */
    private Long vocabularyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_words.line_number
     *
     * @mbg.generated
     */
    private Integer lineNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_words.correct
     *
     * @mbg.generated
     */
    private Integer correct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_words.id
     *
     * @return the value of exercise_words.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_words.id
     *
     * @param id the value for exercise_words.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_words.exercise_id
     *
     * @return the value of exercise_words.exercise_id
     *
     * @mbg.generated
     */
    public Long getExerciseId() {
        return exerciseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_words.exercise_id
     *
     * @param exerciseId the value for exercise_words.exercise_id
     *
     * @mbg.generated
     */
    public void setExerciseId(Long exerciseId) {
        this.exerciseId = exerciseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_words.vocabulary_id
     *
     * @return the value of exercise_words.vocabulary_id
     *
     * @mbg.generated
     */
    public Long getVocabularyId() {
        return vocabularyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_words.vocabulary_id
     *
     * @param vocabularyId the value for exercise_words.vocabulary_id
     *
     * @mbg.generated
     */
    public void setVocabularyId(Long vocabularyId) {
        this.vocabularyId = vocabularyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_words.line_number
     *
     * @return the value of exercise_words.line_number
     *
     * @mbg.generated
     */
    public Integer getLineNumber() {
        return lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_words.line_number
     *
     * @param lineNumber the value for exercise_words.line_number
     *
     * @mbg.generated
     */
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_words.correct
     *
     * @return the value of exercise_words.correct
     *
     * @mbg.generated
     */
    public Integer getCorrect() {
        return correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_words.correct
     *
     * @param correct the value for exercise_words.correct
     *
     * @mbg.generated
     */
    public void setCorrect(Integer correct) {
        this.correct = correct;
    }
}