package org.noodle.orm.model;

public class Recite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recite.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recite.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recite.recite_time
     *
     * @mbg.generated
     */
    private Long reciteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recite.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recite.id
     *
     * @return the value of recite.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recite.id
     *
     * @param id the value for recite.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recite.user_id
     *
     * @return the value of recite.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recite.user_id
     *
     * @param userId the value for recite.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recite.recite_time
     *
     * @return the value of recite.recite_time
     *
     * @mbg.generated
     */
    public Long getReciteTime() {
        return reciteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recite.recite_time
     *
     * @param reciteTime the value for recite.recite_time
     *
     * @mbg.generated
     */
    public void setReciteTime(Long reciteTime) {
        this.reciteTime = reciteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recite.comment
     *
     * @return the value of recite.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recite.comment
     *
     * @param comment the value for recite.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}