package org.noodle.orm.model;

public class ReviewWords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_words.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_words.review_id
     *
     * @mbg.generated
     */
    private Long reviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_words.words_id
     *
     * @mbg.generated
     */
    private Long wordsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_words.id
     *
     * @return the value of review_words.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_words.id
     *
     * @param id the value for review_words.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_words.review_id
     *
     * @return the value of review_words.review_id
     *
     * @mbg.generated
     */
    public Long getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_words.review_id
     *
     * @param reviewId the value for review_words.review_id
     *
     * @mbg.generated
     */
    public void setReviewId(Long reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_words.words_id
     *
     * @return the value of review_words.words_id
     *
     * @mbg.generated
     */
    public Long getWordsId() {
        return wordsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_words.words_id
     *
     * @param wordsId the value for review_words.words_id
     *
     * @mbg.generated
     */
    public void setWordsId(Long wordsId) {
        this.wordsId = wordsId;
    }
}