package org.noodle.orm.model;

public class UserDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dictionary.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dictionary.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dictionary.dictionary_id
     *
     * @mbg.generated
     */
    private Long dictionaryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dictionary.id
     *
     * @return the value of user_dictionary.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dictionary.id
     *
     * @param id the value for user_dictionary.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dictionary.user_id
     *
     * @return the value of user_dictionary.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dictionary.user_id
     *
     * @param userId the value for user_dictionary.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dictionary.dictionary_id
     *
     * @return the value of user_dictionary.dictionary_id
     *
     * @mbg.generated
     */
    public Long getDictionaryId() {
        return dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dictionary.dictionary_id
     *
     * @param dictionaryId the value for user_dictionary.dictionary_id
     *
     * @mbg.generated
     */
    public void setDictionaryId(Long dictionaryId) {
        this.dictionaryId = dictionaryId;
    }
}