package org.noodle.orm.model;

public class Vocabulary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.words_id
     *
     * @mbg.generated
     */
    private Long wordsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.review_time
     *
     * @mbg.generated
     */
    private Integer reviewTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.review_schedule_time1
     *
     * @mbg.generated
     */
    private Long reviewScheduleTime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.review_schedule_time2
     *
     * @mbg.generated
     */
    private Long reviewScheduleTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.review_schedule_time3
     *
     * @mbg.generated
     */
    private Long reviewScheduleTime3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vocabulary.review_schedule_time4
     *
     * @mbg.generated
     */
    private Long reviewScheduleTime4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.id
     *
     * @return the value of vocabulary.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.id
     *
     * @param id the value for vocabulary.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.user_id
     *
     * @return the value of vocabulary.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.user_id
     *
     * @param userId the value for vocabulary.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.words_id
     *
     * @return the value of vocabulary.words_id
     *
     * @mbg.generated
     */
    public Long getWordsId() {
        return wordsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.words_id
     *
     * @param wordsId the value for vocabulary.words_id
     *
     * @mbg.generated
     */
    public void setWordsId(Long wordsId) {
        this.wordsId = wordsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.review_time
     *
     * @return the value of vocabulary.review_time
     *
     * @mbg.generated
     */
    public Integer getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.review_time
     *
     * @param reviewTime the value for vocabulary.review_time
     *
     * @mbg.generated
     */
    public void setReviewTime(Integer reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.review_schedule_time1
     *
     * @return the value of vocabulary.review_schedule_time1
     *
     * @mbg.generated
     */
    public Long getReviewScheduleTime1() {
        return reviewScheduleTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.review_schedule_time1
     *
     * @param reviewScheduleTime1 the value for vocabulary.review_schedule_time1
     *
     * @mbg.generated
     */
    public void setReviewScheduleTime1(Long reviewScheduleTime1) {
        this.reviewScheduleTime1 = reviewScheduleTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.review_schedule_time2
     *
     * @return the value of vocabulary.review_schedule_time2
     *
     * @mbg.generated
     */
    public Long getReviewScheduleTime2() {
        return reviewScheduleTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.review_schedule_time2
     *
     * @param reviewScheduleTime2 the value for vocabulary.review_schedule_time2
     *
     * @mbg.generated
     */
    public void setReviewScheduleTime2(Long reviewScheduleTime2) {
        this.reviewScheduleTime2 = reviewScheduleTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.review_schedule_time3
     *
     * @return the value of vocabulary.review_schedule_time3
     *
     * @mbg.generated
     */
    public Long getReviewScheduleTime3() {
        return reviewScheduleTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.review_schedule_time3
     *
     * @param reviewScheduleTime3 the value for vocabulary.review_schedule_time3
     *
     * @mbg.generated
     */
    public void setReviewScheduleTime3(Long reviewScheduleTime3) {
        this.reviewScheduleTime3 = reviewScheduleTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vocabulary.review_schedule_time4
     *
     * @return the value of vocabulary.review_schedule_time4
     *
     * @mbg.generated
     */
    public Long getReviewScheduleTime4() {
        return reviewScheduleTime4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vocabulary.review_schedule_time4
     *
     * @param reviewScheduleTime4 the value for vocabulary.review_schedule_time4
     *
     * @mbg.generated
     */
    public void setReviewScheduleTime4(Long reviewScheduleTime4) {
        this.reviewScheduleTime4 = reviewScheduleTime4;
    }
}